### ISSUE TITLE
Missing Community Section

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/website#10]
We need to add a community section bellow guides, that adds allows people to find how to get involved in the Pest community.

The section needs to have: Discord link, our Twitter account, etc.

Example: https://tailwindcss.com/community

**Comment by AlexMartinFR** [comment]
Should we have a separate page for everything related to contributing?

Like so:

![image](https://user-images.githubusercontent.com/19224681/82657599-e81a9280-9c25-11ea-9604-7b630797eebf.png)

**Comment by nunomaduro** [comment]
Sounds great!

**Comment by AlexMartinFR** [comment]
I've a community page on the way, though I think you should be the one providing the invite link on the Discord channel, @nunomaduro , so I'll let you add it!

**Comment by nunomaduro** [comment]
Good job!
