### ISSUE TITLE
Menu : active page indicator

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/website#15]
I see the website has everything needed to get an active page indicator in the menu.
I think it would help the navigation.

Should we add one?

It could stand out of the way:
<img width="1219" alt="Capture d’écran 2020-05-24 à 15 01 16" src="https://user-images.githubusercontent.com/19224681/82754769-9b72bb00-9dcf-11ea-80b5-66fe9efc1298.png">

Or a bit more colourful to stay on brand:
<img width="1209" alt="Capture d’écran 2020-05-24 à 14 50 43" src="https://user-images.githubusercontent.com/19224681/82754589-13d87c80-9dce-11ea-9a2f-aff3a831f6a6.png">

(These are from Tailwind's default colour palette)

**Comment by nunomaduro** [comment]
https://github.com/pestphp/website/pull/16
