### ISSUE TITLE
Adding Service Worker for offline support

### ISSUE THREAD

**Issue by octoper** [pestphp/website#23]
I'm considering to add Service Workers so the documentation has offline support, or for better speed on slow connection.
Let me know what you think!

**Comment by nunomaduro** [comment]
@octoper I don't have expertises on that. I am sorry.

**Comment by octoper** [comment]
I can make it but I just asking if I should add it.

**Comment by AlexMartinFR** [comment]
What would the drawbacks be with this?
Do you have an example of a project using them to look at the implementation?

I'm not familiar with them either, but I'm curious.

**Comment by octoper** [comment]
Service workers are used used to create PWA apps.

Twitter has made a very good implementation, if you want to check it out open [twitter.com](https://twitter.com) on Chrome and in the address bar you must see a + button, and you can install Twitter and it will be almost like a native app.

I want to make that for the offline part and because service workers caches all static files the Pest website it will be very fast!
