### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by AlexMartinFR** [pestphp/website#31]
Our documentation might benefit from a style guide to ensure coherence throughout all future contributions.

I've identified a few legibility issues that I want to fix:

<img width="901" alt="Capture d’écran 2020-05-28 à 22 09 33" src="https://user-images.githubusercontent.com/19224681/83188636-4ec11400-a130-11ea-88f9-03203bed3625.png">

- I've put too many things in code blocks, it's visually distracting.
I'm experimenting with putting **filenames inside italics**, and **values inside code blocks** now.

- As we did for the composer.json part, the note about PHPUnit.xml could be a separate step.
It should make reading through the guide a more **fluid experience**.

If you see something that can be improved, feel free to chime in. 🙂

« One thousand pairs or eyes are better than one. »
Me, sometime in 2020.

**Comment by nunomaduro** [comment]
@AlexMartinFR Can you move this one too? Thanks!

**Comment by AlexMartinFR** [comment]
I'll move it with a new screenshot once the new Installation docs page is up, since most of what was mentioned here will need to be changed ;)
